apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
#  annotations:
#    volume-pvc: awsebd
spec:
  accessModes:
  - ReadWriteOnce
  - ReadOnlyMany
  resources:
    requests:
      storage: 5Gi
