apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-deploy
  labels:
    env: prod
spec:
  selector:
    matchLabels:
      env: prod      
  replicas: 5
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 2
      maxSurge: 2
  template:
    metadata:
      labels:
        app: hello-apache
        env: prod
        version: 1.0.1
    spec:
      containers:
      - name: hello-pod
        image: httpd:latest 
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 5
        #resources:
        #  limits:
        #    memory: "128Mi"
        #    cpu: "200m"

