apiVersion: v1
kind: Pod
metadata:
  name: pod-hostpath
  labels:
    env: prod
spec:
#  nodeSelector:
#        kubernetes.io/hostname: <hostname>
  volumes:
    - name: hostpath-vol
      hostPath:
        path: /data
        type: Directory
  containers:
    - name: web-service
      image: httpd:latest
      volumeMounts:
        - name: hostpath-vol
          mountPath: /usr/local/apache2/htdocs

