apiVersion: v1
kind: Pod
spec:
  volumes:
    - name: sitefiles
      emptyDir: {}
  containers:
  - name: nginx
    image: nginx:latest
    volumeMounts:
      - name: sitefiles
        mountPath: /usr/share/nginx/html
        readOnly: true
  - name: html-updater
    image: alpine
    command: ["/bin/sh", "-c"]
    args:
      - while true; do date >> /html/index.html; sleep 10; done
    volumeMounts:
      - name: sitefiles
        mountPath: /html
