apiVersion: v1
kind: Pod
metadata:
  name: my-Pod
spec:
  volumes:
  - name: data
    awsElasticBlockStore:
      volumeID: vol-0824a26074e41bcea
      fsType: ext4
  containers:
  - image: ganeshhp/petclinic_01132021:latest
    name: tomcat-app
    volumeMounts:
    - name: data
      mountPath: /opt/tomcat/webapps