apiVersion: v1
kind: Pod
metadata:
  name: apache-pod
  labels:
    zone: prod
    version: v1
spec:
  containers:
  - name: hello-apache
    image: ganeshhp/webapplication:1.10
    ports:
    - containerPort: 80
