apiVersion: v1
kind: ReplicationController
metadata:
  name: hello-apache-rc
spec:
  replicas: 3
  selector:
        env: dev
  template:
    metadata:
      labels:
        zone: prod
        env: dev
    spec:
      containers:
      - name: apache-pod
        image: ganeshhp/webapplication:1.10
        ports:
        - containerPort: 80

