apiVersion: v1
kind: ReplicationController
metadata:
  name: hello-apache-rc
spec:
  replicas: 5
  selector:
        env: dev
  template:
    metadata:
      labels:
        zone: prod
        env: dev
    spec:
      containers:
      - name: apache-pod
        image: httpd:latest
        ports:
        - containerPort: 80

